[book]
authors = ["Belgarus"]
language = "de"
multilingual = false
src = "src"
title = "wk_wirtschaftliche_grundlagen"

[preprocessor]
[preprocessor.mermaid]
command = "mdbook-mermaid"

[output]
[output.html]
git-repository-url = "https://github.com/Belgarus/Notes"